"""No-network tests for the repository-native Feed deployment boundary."""

from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime, timedelta
from pathlib import Path
from types import SimpleNamespace

import pytest

from follow_the_money.config import load_config
from follow_the_money.config.model import AppConfig, RatePolicy
from follow_the_money.feed import deployment
from follow_the_money.feed.bundle import build_bundle
from follow_the_money.feed.checkpoint import (
    FeedCheckpoint,
    PreviousSuccess,
    read_checkpoint,
    write_checkpoint,
)
from follow_the_money.feed.cli import FeedExecutionError, FeedInputError, FeedRunResult
from follow_the_money.feed.deployment import (
    DeploymentError,
    allowlisted_paths,
    assert_feed_admitted,
    publish_generated_state,
    read_lease,
)
from follow_the_money.feed.deployment import (
    finalize_deployment as _finalize_deployment,
)
from follow_the_money.feed.deployment import (
    prepare_deployment as _prepare_deployment,
)
from follow_the_money.feed.plan import plan_window
from follow_the_money.feed.publish import publish_bundle
from follow_the_money.feed.validate import recompute_feed_identity
from follow_the_money.providers.rate import RateRegistry

NOW = datetime(2026, 8, 29, 0, 0, tzinfo=UTC)
REPO_ROOT = Path(__file__).resolve().parents[1]

# Trusted production baseline: commit f7095a5 ("feeds: failure") is the last
# runtime state generated by the GitHub Hosted Runner before commit 139a0b0
# contaminated `.feed-state/` and `feeds/` with locally generated state.
PRODUCTION_STATE_COMMIT = "f7095a5"
# Registry `root_identity` recorded by the Hosted Runner in that commit.
PRODUCTION_REGISTRY_ROOT = "/home/runner/work/follow-the-money/follow-the-money/.feed-state"
# The restored lease is terminal (state=failure, recovery boundary
# 2026-09-11T05:03:50.415Z already elapsed); any later clock admits preparation.
RECOVERY_ELAPSED = datetime(2026, 9, 12, 0, 0, tzinfo=UTC)
# Real checkpoint continuity pinned by the migration fixtures.
PRODUCTION_CUTOFF = "2026-09-08T04:50:10.689Z"


@pytest.fixture(scope="session")
def production_config() -> AppConfig:
    return load_config(
        REPO_ROOT / "config" / "config.yaml",
        REPO_ROOT / "config" / "providers.yaml",
        manifest_root=REPO_ROOT / "providers",
        require_verified_enabled=True,
    )


def _git_blob(commit: str, path: str) -> bytes:
    completed = subprocess.run(
        ["git", "show", f"{commit}:{path}"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
    )
    return completed.stdout


def _git_tree_names(commit: str, path: str) -> list[str]:
    completed = subprocess.run(
        ["git", "ls-tree", "--name-only", f"{commit}:{path}"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.splitlines()


def build_production_runtime_state(
    runtime_root: Path, *, commit: str = PRODUCTION_STATE_COMMIT
) -> None:
    """Materialize the trusted ``f7095a5`` production runtime state into ``runtime_root``.

    Provenance: every file is extracted verbatim from the git blobs of commit
    ``f7095a5`` ("feeds: failure") — the checkpoint, terminal-failure lease,
    RateRegistry, and all four rate scope files (including the tolerated
    obsolete ``yahoo_market`` scope ``scope-3b806f91752a2756.json``).

    Rewrite rule: the builder replaces the registry's ``root_identity`` (the
    GitHub Hosted Runner path recorded in production) with the fixture
    runtime root's ``resolve()`` so the fail-closed registry check accepts the
    temporary fixture root. This rewrite happens inside the test builder only;
    production restores never rewrite ``root_identity``.
    """
    runtime_root.mkdir(parents=True, exist_ok=True)
    for name in _git_tree_names(commit, ".feed-state"):
        (runtime_root / name).write_bytes(_git_blob(commit, f".feed-state/{name}"))
    registry_path = runtime_root / "rate-registry.json"
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    assert registry["root_identity"] == PRODUCTION_REGISTRY_ROOT
    registry["root_identity"] = str(runtime_root.resolve())
    registry_path.write_text(
        json.dumps(registry, sort_keys=True, separators=(",", ":")), encoding="utf-8"
    )


def build_production_state_fixture(
    runtime_root: Path, product_root: Path, *, commit: str = PRODUCTION_STATE_COMMIT
) -> None:
    """Materialize the trusted ``f7095a5`` runtime state and v3 Feed product.

    Same provenance and rewrite rule as ``build_production_runtime_state``;
    additionally extracts the v3 eight-domain Feed bundle inventoried by
    ``feeds/feed-manifest.json`` into ``product_root`` verbatim. The v3
    product is used only to pin the fail-closed rejection of this bundle as a
    migration input under the current accepted contracts (ECO-124 changed
    cftc's ``empty_valid_for_window``); production restores never place it in
    ``feeds/``.
    """
    build_production_runtime_state(runtime_root, commit=commit)
    product_root.mkdir(parents=True, exist_ok=True)
    for name in _git_tree_names(commit, "feeds"):
        (product_root / name).write_bytes(_git_blob(commit, f"feeds/{name}"))


def build_v4_product(product_root: Path) -> dict:
    """Replace the fixture product root with a current five-domain v4 bundle."""
    feed = _healthy_feed()
    bundle = build_bundle(feed)
    product_root.mkdir(parents=True, exist_ok=True)
    publish_bundle(
        output_root=product_root,
        bundle=bundle,
        cutoff=datetime.fromisoformat(feed["evidence_cutoff_at"]),
        run_id=feed["run_id"],
    )
    return feed


def prepare_production_fixture(
    tmp_path: Path, config: AppConfig, *, deployment_run_id: str, now: datetime
):
    return _prepare_deployment(
        tmp_path / "feeds",
        tmp_path / ".feed-state",
        config,
        deployment_run_id=deployment_run_id,
        now=_clock(now),
    )


def prepare_deployment(root: Path, config, **kwargs):
    return _prepare_deployment(_product_root(root), root, config, **kwargs)


def finalize_deployment(root: Path, **kwargs):
    return _finalize_deployment(_product_root(root), root, **kwargs)


def _product_root(root: Path) -> Path:
    return root.parent / f"{root.name}-products"


def _cfg(*policies: RatePolicy, cooldown_hours: int = 24):
    return SimpleNamespace(
        feed=SimpleNamespace(pre_commit_deadline_seconds=300),
        rate_registry=SimpleNamespace(
            version="1", schema_file="rate-registry.json", crash_cooldown_hours=cooldown_hours
        ),
        providers=tuple(SimpleNamespace(enabled=True, rate_policy=policy) for policy in policies),
    )


def _policy(scope_id: str = "scope-a", **changes: int) -> RatePolicy:
    values = {
        "scope_id": scope_id,
        "capacity": 10,
        "refill_period_seconds": 60,
        "minimum_interval_seconds": 5,
    }
    values.update(changes)
    return RatePolicy(**values)


def _clock(value: datetime):
    return lambda: value


def _healthy_feed() -> dict:
    from tests.test_feed_bundle import _feed

    def shift(value):
        if isinstance(value, dict):
            return {key: shift(item) for key, item in value.items()}
        if isinstance(value, list):
            return [shift(item) for item in value]
        if isinstance(value, str):
            return value.replace("2026-08-11", "2026-08-30")
        return value

    feed = shift(_feed())
    feed["content_digest"], feed["run_id"] = recompute_feed_identity(feed)
    return feed


def test_lease_parser_is_closed_and_versioned(tmp_path: Path):
    path = tmp_path / "feed-run-lease.json"
    path.write_text(
        json.dumps(
            {
                "version": "1",
                "deployment_run_id": "42-1",
                "state": "bootstrap",
                "armed_at": "2026-08-29T00:00:00Z",
                "finished_at": None,
                "feed_start_not_after": None,
                "recovery_not_before": "2026-08-30T00:00:00Z",
                "unexpected": True,
            }
        ),
        encoding="utf-8",
    )
    with pytest.raises(DeploymentError, match="unknown lease fields"):
        read_lease(path)


def test_clean_bootstrap_establishes_zero_network_state(tmp_path: Path):
    result = prepare_deployment(
        tmp_path,
        _cfg(_policy()),
        deployment_run_id="42-1",
        now=_clock(NOW),
    )
    assert result.mode == "bootstrap"
    assert read_lease(tmp_path / "feed-run-lease.json").state == "bootstrap"
    registry = RateRegistry(tmp_path)
    assert registry.registry_path.exists()
    assert registry.recover_or_load("scope-a").tokens == "10"


def test_orphaned_scope_state_blocks_bootstrap_without_mutation(tmp_path: Path):
    orphan = tmp_path / "scope-0123456789abcdef.json"
    orphan.write_text("{}", encoding="utf-8")

    with pytest.raises(DeploymentError, match="partial deployment state"):
        prepare_deployment(
            tmp_path,
            _cfg(_policy()),
            deployment_run_id="42-1",
            now=_clock(NOW),
        )

    assert not (tmp_path / ".follow-the-money-persistent").exists()
    assert not (tmp_path / "rate-registry.json").exists()


def test_prepare_refreshes_repository_before_loading_authoritative_config(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    events: list[str] = []
    monkeypatch.setattr(deployment, "refresh_repository", lambda _repo: events.append("refresh"))

    from follow_the_money.feed import cli

    monkeypatch.setattr(cli, "_load_app_config", lambda _path: events.append("load") or _cfg())
    monkeypatch.setattr(
        deployment,
        "prepare_deployment",
        lambda *_args, **_kwargs: SimpleNamespace(mode="bootstrap"),
    )

    assert (
        deployment._command_prepare(
            SimpleNamespace(
                config=None,
                repo=str(tmp_path),
                product_root=str(tmp_path / "feeds"),
                runtime_state_root=str(tmp_path / ".feed-state"),
                run_id="42-1",
                output=None,
            )
        )
        == 0
    )
    assert events == ["refresh", "load"]


def test_bootstrap_before_quiet_boundary_blocks(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    with pytest.raises(DeploymentError, match="recovery_not_before"):
        prepare_deployment(
            tmp_path,
            _cfg(_policy()),
            deployment_run_id="43-1",
            now=_clock(NOW + timedelta(hours=1)),
        )


def test_established_state_arms_after_boundary_with_conservative_bounds(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    armed_at = NOW + timedelta(hours=24)
    result = prepare_deployment(
        tmp_path,
        _cfg(_policy()),
        deployment_run_id="43-1",
        now=_clock(armed_at),
    )
    lease = read_lease(tmp_path / "feed-run-lease.json")
    assert result.mode == "armed"
    assert lease.state == "in_progress"
    assert lease.feed_start_not_after == armed_at + timedelta(seconds=300)
    assert lease.recovery_not_before == armed_at + timedelta(seconds=300 + 300 + 24 * 3600)


def test_missing_or_corrupt_established_state_fails_closed(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    (tmp_path / "rate-registry.json").unlink()
    with pytest.raises(DeploymentError):
        prepare_deployment(
            tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(NOW + timedelta(days=2))
        )


@pytest.mark.parametrize(
    ("scope_payload", "replacement"),
    [
        (None, []),
        ("tokens", "not-a-number"),
        ("refill_wall_anchor", "not-a-timestamp"),
    ],
)
def test_corrupt_scope_state_fails_as_typed_deployment_error(
    tmp_path: Path, scope_payload: str | None, replacement: object
):
    result = prepare_deployment(
        tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW)
    )
    scope_path = next(path for path in result.paths if path.name.startswith("scope-"))
    payload = json.loads(scope_path.read_text(encoding="utf-8"))
    if scope_payload is None:
        payload = replacement
    else:
        payload[scope_payload] = replacement
    scope_path.write_text(json.dumps(payload), encoding="utf-8")

    with pytest.raises(DeploymentError):
        prepare_deployment(
            tmp_path,
            _cfg(_policy()),
            deployment_run_id="43-1",
            now=_clock(NOW + timedelta(days=2)),
        )


def test_new_scope_uses_rate_registry_first_use_before_arming(tmp_path: Path):
    cfg = _cfg(_policy())
    prepare_deployment(tmp_path, cfg, deployment_run_id="42-1", now=_clock(NOW))
    next_run = NOW + timedelta(days=1)
    result = prepare_deployment(
        tmp_path,
        _cfg(_policy(), _policy("scope-b")),
        deployment_run_id="43-1",
        now=_clock(next_run),
    )
    assert result.mode == "armed"
    assert RateRegistry(tmp_path).recover_or_load("scope-b").tokens == "10"


def test_recovery_rejects_resolved_policy_outside_envelope_without_provider_ids(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    with pytest.raises(DeploymentError, match="recovery envelope"):
        prepare_deployment(
            tmp_path,
            _cfg(_policy(refill_period_seconds=24 * 3600 + 1)),
            deployment_run_id="43-1",
            now=_clock(NOW + timedelta(days=1)),
        )


def test_missed_feed_start_bound_blocks_admission(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    armed_at = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(armed_at))
    with pytest.raises(DeploymentError, match="feed_start_not_after"):
        assert_feed_admitted(
            tmp_path,
            deployment_run_id="43-1",
            now=armed_at + timedelta(seconds=301),
        )


def test_in_progress_recovery_blocks_before_and_allows_after_boundary(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    armed_at = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(armed_at))
    recovery = armed_at + timedelta(seconds=300 + 300 + 24 * 3600)
    with pytest.raises(DeploymentError, match="recovery_not_before"):
        prepare_deployment(
            tmp_path,
            _cfg(_policy()),
            deployment_run_id="44-1",
            now=_clock(recovery - timedelta(seconds=1)),
        )
    assert (
        prepare_deployment(
            tmp_path,
            _cfg(_policy()),
            deployment_run_id="44-1",
            now=_clock(recovery),
        ).mode
        == "armed"
    )


def test_terminal_lease_does_not_delay_next_daily_run(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    first_run = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(first_run))
    finalize_deployment(
        tmp_path,
        deployment_run_id="43-1",
        feed_succeeded=False,
        status_path=tmp_path / "unused-status.json",
        now=_clock(first_run + timedelta(seconds=1)),
    )

    assert (
        prepare_deployment(
            tmp_path,
            _cfg(_policy()),
            deployment_run_id="44-1",
            now=_clock(first_run + timedelta(days=1)),
        ).mode
        == "armed"
    )


def test_success_and_failure_finalization_keep_exact_paths(tmp_path: Path):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    armed_at = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(armed_at))
    feed = _healthy_feed()
    run_id = feed["run_id"]
    _product_root(tmp_path).mkdir(parents=True)
    bundle = build_bundle(feed)
    publish_bundle(
        output_root=_product_root(tmp_path),
        bundle=bundle,
        cutoff=datetime.fromisoformat(feed["evidence_cutoff_at"]),
        run_id=run_id,
    )
    status = tmp_path / "feed-status.json"
    status.write_text(
        json.dumps(
            {
                "status": "healthy",
                "run_id": run_id,
                "evidence_cutoff_at": feed["evidence_cutoff_at"],
                "manifest_relative_path": "feed-manifest.json",
            }
        ),
        encoding="utf-8",
    )
    write_checkpoint(
        tmp_path / "feed-checkpoint.json",
        FeedCheckpoint(
            previous_success=PreviousSuccess(
                evidence_cutoff_at=feed["evidence_cutoff_at"],
                run_id=run_id,
            )
        ),
    )
    paths = finalize_deployment(
        tmp_path,
        deployment_run_id="43-1",
        feed_succeeded=True,
        status_path=status,
        now=_clock(armed_at + timedelta(seconds=1)),
    )
    assert {path.name for path in paths} >= {"feed-run-lease.json", "feed-manifest.json"}
    assert read_lease(tmp_path / "feed-run-lease.json").state == "success"

    prepare_deployment(
        tmp_path,
        _cfg(_policy()),
        deployment_run_id="44-1",
        now=_clock(armed_at + timedelta(days=2)),
    )
    failure_paths = finalize_deployment(
        tmp_path,
        deployment_run_id="44-1",
        feed_succeeded=False,
        status_path=status,
        now=_clock(armed_at + timedelta(days=2, seconds=1)),
    )
    assert all(path.name not in {"latest.json", f"{run_id}.json"} for path in failure_paths)
    assert read_lease(tmp_path / "feed-run-lease.json").state == "failure"


def test_source_completeness_failure_finalization_preserves_status_and_allowlist(
    tmp_path: Path,
):
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW))
    armed_at = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(armed_at))
    status = tmp_path / "feed-status.json"
    payload = {
        "status": "failure",
        "warnings": [
            "source incomplete: provider_id=bls state=failed error=provider unavailable",
        ],
    }
    status.write_text(json.dumps(payload), encoding="utf-8")

    paths = finalize_deployment(
        tmp_path,
        deployment_run_id="43-1",
        feed_succeeded=False,
        status_path=status,
        now=_clock(armed_at + timedelta(seconds=1)),
    )

    assert json.loads(status.read_text(encoding="utf-8")) == payload
    assert set(paths) == set(allowlisted_paths(tmp_path))
    assert status not in allowlisted_paths(tmp_path)
    assert read_lease(tmp_path / "feed-run-lease.json").state == "failure"
    assert not (tmp_path / "latest.json").exists()
    assert not (tmp_path / "daily").exists()


def test_success_finalization_rejects_non_feed_status_paths(tmp_path: Path):
    result = prepare_deployment(
        tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW)
    )
    scope_path = next(path for path in result.paths if path.name.startswith("scope-"))
    armed_at = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(armed_at))
    feed = _healthy_feed()
    run_id = feed["run_id"]
    _product_root(tmp_path).mkdir(parents=True)
    status = tmp_path / "feed-status.json"
    status.write_text(
        json.dumps(
            {
                "status": "healthy",
                "run_id": run_id,
                "evidence_cutoff_at": "2026-08-30T00:20:00Z",
                "manifest_relative_path": scope_path.name,
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(DeploymentError, match="manifest_relative_path"):
        finalize_deployment(
            tmp_path,
            deployment_run_id="43-1",
            feed_succeeded=True,
            status_path=status,
            now=_clock(armed_at + timedelta(seconds=1)),
        )


def test_finalization_keeps_in_progress_when_exact_rate_state_is_missing(tmp_path: Path):
    result = prepare_deployment(
        tmp_path, _cfg(_policy()), deployment_run_id="42-1", now=_clock(NOW)
    )
    armed_at = NOW + timedelta(days=1)
    prepare_deployment(tmp_path, _cfg(_policy()), deployment_run_id="43-1", now=_clock(armed_at))
    next(path for path in result.paths if path.name.startswith("scope-")).unlink()

    with pytest.raises(DeploymentError, match="missing/partial"):
        finalize_deployment(
            tmp_path,
            deployment_run_id="43-1",
            feed_succeeded=False,
            status_path=tmp_path / "unused-status.json",
            now=_clock(armed_at + timedelta(seconds=1)),
        )

    assert read_lease(tmp_path / "feed-run-lease.json").state == "in_progress"


def test_git_publication_is_non_force_and_stages_only_allowlist(tmp_path: Path):
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "test"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=tmp_path, check=True)
    (tmp_path / "feeds").mkdir()
    (tmp_path / "feeds/feed-run-lease.json").write_text("{}", encoding="utf-8")
    (tmp_path / "unrelated.txt").write_text("do not stage", encoding="utf-8")
    subprocess.run(["git", "add", "feeds/feed-run-lease.json"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "base"], cwd=tmp_path, check=True)
    (tmp_path / "feeds/feed-run-lease.json").write_text('{"state":"success"}', encoding="utf-8")
    calls: list[list[str]] = []

    def git(args: list[str]) -> str:
        calls.append(args)
        if args[:2] == ["push", "origin"]:
            raise DeploymentError("push conflict")
        completed = subprocess.run(
            ["git", *args], cwd=tmp_path, check=True, text=True, capture_output=True
        )
        return completed.stdout

    with pytest.raises(DeploymentError, match="push conflict"):
        publish_generated_state(
            tmp_path,
            [tmp_path / "feeds/feed-run-lease.json"],
            message="feeds: arm",
            git=git,
        )
    committed = subprocess.run(
        ["git", "show", "--format=", "--name-only", "HEAD"],
        cwd=tmp_path,
        check=True,
        text=True,
        capture_output=True,
    ).stdout.splitlines()
    assert committed == ["feeds/feed-run-lease.json"]
    assert (
        not (tmp_path / "unrelated.txt").exists()
        or (tmp_path / "unrelated.txt").read_text() == "do not stage"
    )
    assert all("--force" not in call for call in calls)


def test_failed_feed_status_preserves_existing_failure_facts_without_parsing_warnings(
    tmp_path: Path,
):
    outcomes = [
        {
            "provider_id": "bls",
            "state": "failed",
            "error": "HTTP 403",
            "attempted": 1,
            "fetched": 0,
            "accepted": 0,
            "rejected": 2,
        },
        {
            "provider_id": "sec_edgar",
            "state": "empty",
            "error": None,
            "attempted": 1,
            "fetched": 1,
            "accepted": 0,
            "rejected": 0,
        },
    ]
    warnings = ["opaque warning: provider_id=not-a-fact state=not-a-state"]
    status_path = tmp_path / "feed-status.json"

    deployment._write_feed_status(
        status_path,
        FeedRunResult(
            status="failure",
            exit_code=1,
            feed={"provider_outcomes": outcomes},
            warnings=warnings,
            message="source completeness failed",
        ),
    )

    assert json.loads(status_path.read_text(encoding="utf-8")) == {
        "status": "failure",
        "message": "source completeness failed",
        "warnings": warnings,
        "provider_outcomes": outcomes,
    }


@pytest.mark.parametrize(
    ("error", "expected_code"),
    [
        (FeedInputError("execution failed: invalid input"), 2),
        (FeedExecutionError("input failed: provider execution"), 1),
    ],
)
def test_typed_collect_failures_write_narrow_status_without_provider_facts(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    error: Exception,
    expected_code: int,
):
    from follow_the_money.feed import cli

    monkeypatch.setattr(deployment, "assert_feed_admitted", lambda *_args, **_kwargs: None)

    def fail(**_kwargs):
        raise error

    monkeypatch.setattr(cli, "run_feed", fail)
    status_path = tmp_path / "feed-status.json"
    exit_path = tmp_path / ".feed-exit-code"

    code = deployment._command_collect(
        SimpleNamespace(
            product_root=str(tmp_path / "products"),
            runtime_state_root=str(tmp_path),
            config=None,
            run_id="run-1",
            status_file=str(status_path),
            exit_file=str(exit_path),
        )
    )

    assert code == expected_code
    assert json.loads(status_path.read_text(encoding="utf-8")) == {
        "status": "failure",
        "message": str(error),
        "warnings": [],
    }
    assert "provider_outcomes" not in json.loads(status_path.read_text(encoding="utf-8"))
    assert exit_path.read_text(encoding="utf-8") == str(expected_code)


def test_diagnostics_renderer_selects_known_fields_and_preserves_provider_order(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    status_path = tmp_path / "feed-status.json"
    summary_path = tmp_path / "summary.md"
    status_path.write_text(
        json.dumps(
            {
                "status": "failure",
                "message": "line one\nline two | * [unsafe] \x00",
                "warnings": ["warning\ttext"],
                "provider_outcomes": [
                    {
                        "provider_id": "zeta",
                        "state": "failed",
                        "error": "bad\nerror | `code`",
                        "attempted": 2,
                        "fetched": 1,
                        "accepted": 3,
                        "rejected": 4,
                        "ignored": "must not render",
                    },
                    {
                        "provider_id": "alpha",
                        "state": "partial",
                        "error": "partial error",
                        "attempted": 5,
                        "fetched": 6,
                        "accepted": 7,
                        "rejected": 8,
                    },
                ],
                "ignored": "must not render",
            }
        ),
        encoding="utf-8",
    )

    assert deployment._render_feed_diagnostics(status_path, summary_path) == 0
    rendered = capsys.readouterr().out
    summary = summary_path.read_text(encoding="utf-8")

    assert rendered == summary
    assert rendered.index("provider_id: zeta") < rendered.index("provider_id: alpha")
    for field, value in (
        ("provider_id", "zeta"),
        ("state", "failed"),
        ("error", "bad"),
        ("attempted", "2"),
        ("fetched", "1"),
        ("accepted", "3"),
        ("rejected", "4"),
    ):
        assert f"{field}: {value}" in rendered
    assert "must not render" not in rendered
    assert "\\n" in rendered
    assert "\\t" in rendered
    assert "\\x00" in rendered
    assert "\\|" in rendered
    assert "`code`" not in rendered
    assert "\x00" not in rendered


def test_degraded_diagnostics_render_availability_in_provider_order(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    status_path = tmp_path / "feed-status.json"
    summary_path = tmp_path / "summary.md"
    status_path.write_text(
        json.dumps(
            {
                "status": "degraded",
                "warnings": ["blocked Providers"],
                "provider_outcomes": [
                    {
                        "provider_id": provider_id,
                        "state": "failed",
                        "availability": "blocked",
                        "availability_reason": "HTTP 403",
                        "upstream_http_status": 403,
                        "affected_coverage_groups": groups,
                    }
                    for provider_id, groups in (("sse", ["china"]), ("bls", ["calendar", "macro"]))
                ],
            }
        ),
        encoding="utf-8",
    )

    assert deployment._render_feed_diagnostics(status_path, summary_path) == 0
    rendered = capsys.readouterr().out
    assert rendered == summary_path.read_text(encoding="utf-8")
    assert rendered.index("provider_id: bls") < rendered.index("provider_id: sse")
    assert "availability: blocked" in rendered
    assert "availability_reason: HTTP 403" in rendered
    assert "affected_coverage_groups: calendar, macro" in rendered


def test_diagnostics_renderer_bounds_fields_and_total_output(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    status_path = tmp_path / "feed-status.json"
    status_path.write_text(
        json.dumps(
            {
                "status": "failure",
                "message": "m" * 400,
                "warnings": ["w" * 400],
                "provider_outcomes": [
                    {
                        "provider_id": "provider",
                        "state": "failed",
                        "error": "e" * 400,
                        "attempted": 1,
                        "fetched": 0,
                        "accepted": 0,
                        "rejected": 1,
                    }
                ]
                * 30,
            }
        ),
        encoding="utf-8",
    )

    assert deployment._render_feed_diagnostics(status_path, None) == 0
    rendered = capsys.readouterr().out.rstrip("\n")
    assert len(rendered) <= 4096
    assert len(next(line for line in rendered.splitlines() if line.startswith("message: "))) == 265
    assert (
        len(next(line for line in rendered.splitlines() if line.startswith("warning[1]: "))) == 268
    )
    assert len(next(line for line in rendered.splitlines() if line.startswith("error: "))) == 263


@pytest.mark.parametrize("contents", [None, "{"])
def test_missing_or_corrupt_diagnostics_status_is_bounded_and_non_gating(
    tmp_path: Path, capsys: pytest.CaptureFixture[str], contents: str | None
):
    status_path = tmp_path / "feed-status.json"
    if contents is not None:
        status_path.write_text(contents, encoding="utf-8")

    assert deployment._render_feed_diagnostics(status_path, tmp_path / "summary.md") == 0
    rendered = capsys.readouterr().out
    assert "diagnostics unavailable" in rendered
    assert len(rendered) <= 256
    assert not (tmp_path / "summary.md").exists()


def test_diagnostics_summary_write_failure_is_bounded_and_non_gating(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    status_path = tmp_path / "feed-status.json"
    status_path.write_text(
        json.dumps({"status": "failure", "message": "failure", "warnings": []}),
        encoding="utf-8",
    )
    summary_path = tmp_path / "missing-parent" / "summary.md"

    assert deployment._render_feed_diagnostics(status_path, summary_path) == 0
    rendered = capsys.readouterr().out
    assert "Feed failure diagnostics" in rendered
    assert "diagnostics unavailable" in rendered


def test_diagnostics_command_entry_renders_status_and_summary(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    status_path = tmp_path / "feed-status.json"
    summary_path = tmp_path / "summary.md"
    status_path.write_text(
        json.dumps({"status": "failure", "message": "failure", "warnings": []}),
        encoding="utf-8",
    )

    assert (
        deployment.main(
            [
                "diagnostics",
                "--status-file",
                str(status_path),
                "--summary-file",
                str(summary_path),
            ]
        )
        == 0
    )
    assert capsys.readouterr().out == summary_path.read_text(encoding="utf-8")


# --- restore-feed-production-state: deployment-level regression tests -------
# These tests pin recovery-critical behavior against fixtures extracted from
# the real f7095a5 production blobs (see build_production_state_fixture).


def test_production_state_fixture_round_trips_blobs_except_root_identity(
    tmp_path: Path,
):
    runtime_root = tmp_path / ".feed-state"
    product_root = tmp_path / "feeds"
    build_production_state_fixture(runtime_root, product_root)

    for name in _git_tree_names(PRODUCTION_STATE_COMMIT, ".feed-state"):
        extracted = (runtime_root / name).read_bytes()
        blob = _git_blob(PRODUCTION_STATE_COMMIT, f".feed-state/{name}")
        if name == "rate-registry.json":
            original = json.loads(blob)
            rewritten = json.loads(extracted)
            assert rewritten.pop("root_identity") == str(runtime_root.resolve())
            assert original.pop("root_identity") == PRODUCTION_REGISTRY_ROOT
            assert rewritten == original
        else:
            assert extracted == blob
    for name in _git_tree_names(PRODUCTION_STATE_COMMIT, "feeds"):
        assert (product_root / name).read_bytes() == _git_blob(
            PRODUCTION_STATE_COMMIT, f"feeds/{name}"
        )

    assert {path.name for path in runtime_root.glob("scope-*.json")} == {
        "scope-3b806f91752a2756.json",  # yahoo_market (obsolete, tolerated)
        "scope-9a77456fa49e1cb0.json",  # sec_edgar
        "scope-af0aa41eb4b4225d.json",  # china_gov
        "scope-bf3977c6d08a7675.json",  # us_gov
    }
    checkpoint = json.loads((runtime_root / "feed-checkpoint.json").read_text())
    assert checkpoint["previous_success"]["evidence_cutoff_at"] == PRODUCTION_CUTOFF
    lease = json.loads((runtime_root / "feed-run-lease.json").read_text())
    assert lease["deployment_run_id"] == "34438934934-1"
    assert lease["state"] == "failure"


def test_fixture_root_identity_passes_and_mismatch_fails_closed(
    tmp_path: Path, production_config: AppConfig
):
    build_production_runtime_state(tmp_path / ".feed-state")
    result = prepare_production_fixture(
        tmp_path,
        production_config,
        deployment_run_id="99999999999-1",
        now=RECOVERY_ELAPSED,
    )
    assert result.mode == "armed"

    registry_path = tmp_path / ".feed-state" / "rate-registry.json"
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    registry["root_identity"] = "/some/other/runtime/root"
    registry_path.write_text(
        json.dumps(registry, sort_keys=True, separators=(",", ":")), encoding="utf-8"
    )
    with pytest.raises(DeploymentError, match="root_identity is inconsistent"):
        prepare_production_fixture(
            tmp_path,
            production_config,
            deployment_run_id="99999999999-2",
            now=RECOVERY_ELAPSED,
        )


def test_restored_state_arms_with_checkpoint_continuity_and_bounded_window(
    tmp_path: Path, production_config: AppConfig
):
    build_production_runtime_state(tmp_path / ".feed-state")
    result = prepare_production_fixture(
        tmp_path,
        production_config,
        deployment_run_id="99999999999-1",
        now=RECOVERY_ELAPSED,
    )

    assert result.mode == "armed"
    checkpoint = read_checkpoint(tmp_path / ".feed-state" / "feed-checkpoint.json")
    assert checkpoint.previous_success is not None
    assert checkpoint.previous_success.evidence_cutoff_at == PRODUCTION_CUTOFF
    assert read_lease(tmp_path / ".feed-state" / "feed-run-lease.json").state == ("in_progress")

    # The ~10-day checkpoint gap exceeds the configured maximum: the accepted
    # fixed-advancing-window semantics bound the acquisition to the most
    # recent 72 hours and record the uncovered interval explicitly.
    plan = plan_window(
        cutoff=RECOVERY_ELAPSED + timedelta(days=6),
        previous_success=checkpoint.previous_success,
    )
    assert plan.bootstrap is True
    assert plan.window_start == "2026-09-15T00:00:00.000Z"
    assert plan.gap_warning == (PRODUCTION_CUTOFF, plan.window_start)


def test_real_v3_product_as_migration_input_fails_closed(
    tmp_path: Path, production_config: AppConfig
):
    build_production_state_fixture(tmp_path / ".feed-state", tmp_path / "feeds")
    with pytest.raises(DeploymentError, match="previous Feed bundle migration failed"):
        prepare_production_fixture(
            tmp_path,
            production_config,
            deployment_run_id="99999999999-1",
            now=RECOVERY_ELAPSED,
        )


def test_retained_scopes_keep_real_dispatch_state_through_preparation(
    tmp_path: Path, production_config: AppConfig
):
    build_production_runtime_state(tmp_path / ".feed-state")
    prepare_production_fixture(
        tmp_path,
        production_config,
        deployment_run_id="99999999999-1",
        now=RECOVERY_ELAPSED,
    )

    runtime_root = tmp_path / ".feed-state"
    real_dispatch_state = {
        "scope-bf3977c6d08a7675.json": (  # us_gov
            "2026-09-10T04:53:55.273Z",
            "2026-09-10T04:53:55.273Z",
        ),
        "scope-af0aa41eb4b4225d.json": (  # china_gov
            "2026-09-10T04:54:01.385Z",
            "2026-09-10T04:54:01.385Z",
        ),
        "scope-9a77456fa49e1cb0.json": (  # sec_edgar
            "2026-09-10T04:53:53.274Z",
            "2026-09-10T04:53:53.274Z",
        ),
    }
    for name, (last_dispatch, refill_anchor) in real_dispatch_state.items():
        state = json.loads((runtime_root / name).read_text(encoding="utf-8"))
        assert state["last_dispatch_wall"] == last_dispatch
        assert state["refill_wall_anchor"] == refill_anchor


def test_obsolete_yahoo_market_scope_is_tolerated_and_required(
    tmp_path: Path, production_config: AppConfig
):
    build_production_runtime_state(tmp_path / ".feed-state")
    prepare_production_fixture(
        tmp_path,
        production_config,
        deployment_run_id="99999999999-1",
        now=RECOVERY_ELAPSED,
    )
    yahoo_blob = _git_blob(PRODUCTION_STATE_COMMIT, ".feed-state/scope-3b806f91752a2756.json")
    assert (tmp_path / ".feed-state" / "scope-3b806f91752a2756.json").read_bytes() == yahoo_blob

    build_production_runtime_state(tmp_path / ".feed-state")
    (tmp_path / ".feed-state" / "scope-3b806f91752a2756.json").unlink()
    with pytest.raises(DeploymentError, match="rate scope files are missing/partial"):
        prepare_production_fixture(
            tmp_path,
            production_config,
            deployment_run_id="99999999999-2",
            now=RECOVERY_ELAPSED,
        )


def test_current_v4_product_takes_normal_preparation_path(
    tmp_path: Path, production_config: AppConfig, monkeypatch: pytest.MonkeyPatch
):
    build_production_runtime_state(tmp_path / ".feed-state")
    feed = build_v4_product(tmp_path / "feeds")
    migration_calls: list[object] = []
    monkeypatch.setattr(
        deployment,
        "_migrate_previous_product",
        lambda *_args, **_kwargs: migration_calls.append(_args),
    )

    result = prepare_production_fixture(
        tmp_path,
        production_config,
        deployment_run_id="99999999999-1",
        now=RECOVERY_ELAPSED,
    )

    assert result.mode == "armed"
    assert migration_calls == []
    manifest = json.loads((tmp_path / "feeds" / "feed-manifest.json").read_text(encoding="utf-8"))
    assert manifest["schema_version"] == 4
    assert manifest["run_id"] == feed["run_id"]
    assert read_lease(tmp_path / ".feed-state" / "feed-run-lease.json").state == ("in_progress")
